# fly.toml app configuration file generated for startab-loyiha-dwps1g on 2026-05-07T13:44:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'startab-loyiha-dwps1g'
primary_region = 'ams'
console_command = '/code/manage.py shell'

[build]

[env]
  DJANGO_SETTINGS_MODULE = 'config.settings'
  PORT = '8000'

[http_service]
  internal_port = 7995
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '30s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
