# Generated by Django 5.1.15 on 2026-05-01 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('short_description', models.CharField(max_length=300, verbose_name='Qisqa tavsif')),
                ('description', models.TextField(verbose_name='Batafsil tavsif')),
                ('needed_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Kerakli mablag' (so'm)")),
                ('equity_percent', models.DecimalField(decimal_places=2, help_text='0 dan 100 gacha', max_digits=5, verbose_name='Ulush (%)')),
                ('industry', models.CharField(choices=[('it', 'IT'), ('marketing', 'Marketing'), ('education', "Ta'lim"), ('medicine', 'Tibbiyot'), ('agriculture', "Qishloq xo'jaligi"), ('energy', 'Energiya'), ('logistics', 'Logistika'), ('other', 'Boshqa')], max_length=20, verbose_name='Soha')),
                ('region', models.CharField(choices=[('toshkent_sh', 'Toshkent shahri'), ('toshkent_v', 'Toshkent viloyati'), ('andijon', 'Andijon'), ('buxoro', 'Buxoro'), ('fargona', "Farg'ona"), ('jizzax', 'Jizzax'), ('xorazm', 'Xorazm'), ('namangan', 'Namangan'), ('navoiy', 'Navoiy'), ('qashqadaryo', 'Qashqadaryo'), ('qoraqalpogiston', "Qoraqalpog'iston"), ('samarqand', 'Samarqand'), ('sirdaryo', 'Sirdaryo'), ('surxondaryo', 'Surxondaryo')], max_length=30, verbose_name='Hudud')),
                ('file', models.FileField(blank=True, help_text='JPG, PNG yoki PDF (max 10 MB)', null=True, upload_to='ideas/', verbose_name='Rasm yoki PDF')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('funded', 'Moliyalashtirilgan'), ('closed', 'Yopiq')], default='new', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
            ],
            options={
                'verbose_name': "G'oya",
                'verbose_name_plural': "G'oyalar",
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Taklif qilingan mablag' (so'm)")),
                ('equity_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ulush (%)')),
                ('message', models.TextField(blank=True, verbose_name='Xabar')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilingan'), ('rejected', 'Rad etilgan')], default='pending', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='ideas.idea', verbose_name="G'oya")),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_made', to=settings.AUTH_USER_MODEL, verbose_name='Investor')),
            ],
            options={
                'verbose_name': 'Taklif',
                'verbose_name_plural': 'Takliflar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Matn')),
                ('is_read', models.BooleanField(default=False, verbose_name="Ko'rilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ideas.offer', verbose_name='Taklif')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='SavedIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='ideas.idea', verbose_name="G'oya")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_ideas', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Saqlangan g'oya",
                'verbose_name_plural': "Saqlangan g'oyalar",
                'ordering': ('-created_at',),
                'unique_together': {('user', 'idea')},
            },
        ),
    ]
